### ISSUE TITLE
multiple usage of same calendar

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#10]
is it possible?

**Comment by allan-gam** [comment]
Yes it's definitely possible and it's very useful.

Let's say that you are a student and the school has made a Google Calendar daily school schedule for you.

Then You can define a calendar in GCal so that You wake up in time (and start your coffee machine for example) Put a start offset and a end offset both set to  -80 minutes. However since you may have more than one lesson per day, it can be useful to do some scripting to determine whether it's the first lesson of the day or not. See the example in the wiki. Otherwise you will have a lot of coffee when you come home from school.

Then maybe you'd like to use the same calendar again but in "real" time (no start- or end offsets) to trigger some other events. Maybe you'd like to have your lawn sprinkled whenever there is a math lesson going on.   Then you'd need to filter on a specific keyword, e.g. "math". (Otherwise your lawn might transform into a swamp)

So, for every case where you need different start- or end offsets, or keywords, just define the calendar again using the desired values.

BTW, If it's a school schedule and it's only updated once a year you can define a very high value for "interval" to a week or even more. (1080 = a week). No need to spam Google to update such a calendar every 5 minutes.

**Comment by allan-gam** [comment]
If You define several instances of your calendar using different parameters, be sure to name the devices in Domoticz to something unique and useful so that you can determine which device is for what.

Example: Switch devices: "GCal School Math (-80:-80)", "GCal School Lessons" etc

**Comment by four2six** [comment]
ok, cool, i get what you mean. and it's actually on a different setting something i'd need for something i'm looking for.

i think the main issue why some (including me) might be hesitant to use this extensively might be the scripts. 

i could write a script for something, but after some time i might forget what i actually put in there. then i'd have to drag out my ssh credentials from somewhere, find the script, understand what i wrote half a year ago, etc. etc.

as stupid as blockly is, something visual like that would be much better to handle, directly from the domoticz web interface

**Comment by allan-gam** [comment]
(Updated my comment regarding the interval. 1440 is currently the highest value. If we need to use higher values, we'd need to re-program what is fetched from Google. )

**Comment by four2six** [comment]
just to be 100% sure i understand correctly what it fetches:
the next event in that specific calendar, the number of remaining events that day and the number of total events that day.
if i use a keyword, does that mean the number of events that day and the total number reflect that keyword? so if i have only one event that day that matches the keyword, the total number would be 1, even if there are more events (without that keyword) in the calendar?

**Comment by four2six** [comment]
and: you know the "day" we use here might be ok for a school schedule, but others might have a different "day" they'd want to use. 
for example if you want to turn off the lights at night after you go to bed and you want to base that on certain definitions you add to a calendar, a day might end after midnight.

**Comment by four2six** [comment]
thinking about it: 
you add an event to the calendar that starts at 2200 in the evening, and ends at 0200 in the morning. 
what happens at midnight? will the switch be still on?

**Comment by allan-gam** [comment]
I will soon release an update that allows interval as high as 10080 (One week).

If you use a keyword (or keywords) , then that GCal Calendar instance will only see events that match the keywords. The text device in Domoticz won't be aware of events that doesn't match. 

So, the number of events do reflect the keyword. If you have only one event that day that matches the keyword, the total number would be 1, even if there are more events (without that keyword) in the calendar. ;)

The current "day" should be considered the day in Domoticz perspective. This subject might deserve a separate issue to clarify. 

Events that spans over midnight would/should be treated as 2 events (1 on each day) 

There is a question during setup, "Treat back-to-back events with the same name as one long event". The config entry name for that is "retrip". It's not been implemented yet though, I'm working on it. It needs further investigation to find out how we'd want that to work and also this subject might deserve a separate issue.

**Comment by four2six** [comment]
not sure a daily update is really an issue

**Comment by four2six** [comment]
just make sure the two events (1 on each day) don't trigger the switch to be turned off in between. would be bad if a door opened at midnight or something like that ;-)
