### ISSUE TITLE
tmpfs

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#18]
the optional configuration idea is nice, but those who haven't done that would probably need help for GCal. How do you make sure the important data is not lost? And one might ask: Why doesn't GCal do it for me? ;)

**Comment by allan-gam** [comment]
I have made an additional comment about that in the wiki. That specific topic is quite advanced and it's not specific for GCal. Most users should avoid doing it due to the complexity and the trouble to restore the data in case the server is rebooted. 

It's beyond the scope of GCal to handle or know anything about storage.

Setting up a tmpfs is only for nerds like me who are concerned about not writing to often to the SD card. If you set up a tmpfs you must make sure the server will never reboot or you'd have to keep a backup of the files that are stored in tmpfs and restore them manually.

**Comment by four2six** [comment]
so this doesn't have anything to do in here? it's a nice helpful idea, but i guess it would confuse those who don't know about it and it doesn't help those who already do.

**Comment by allan-gam** [comment]
Yes, thinking about it, you are probably right about that. 

Maybe it can help those who know about the concept and the consequences but doesn't exactly remember how to set it up. 

Let's think about it for a while. With the new version of GCal that can restore the raw Google Calendar Data files if they are missing it makes sense to put them on a tmpfs. I'll give it another thought after the weekend! Cheers!

**Comment by allan-gam** [comment]
Configuration data has now been separated from "state data" that can be restored. 

The dispensable data is put in the temp dir and it wont hurt to put them on a tmpfs in case someone would like to. Configuration data should not be stored on a tmpfs. The Wiki has been updated to reflect this.

**Comment by four2six** [comment]
somehow this should be put in the wiki. i'll do it once i find the time, probably on tuesday. sorry for reopening it for that.
