### ISSUE TITLE
Adding second calendar

### ISSUE THREAD

**Issue by four2six** [allan-gam/GCal#19]
Setup ends with below.
devices are created.

`Can not open the calendar file /var/tmp/GCalData/<secondcalendar>@group.calendar.google.com.json <type 'exceptions.IOError'>`

**Comment by four2six** [comment]
```
pi@raspberrypi /var/tmp $ ls -all
total 12
drwxrwxrwt  3 root root 4096 Apr 27 15:27 .
drwxr-xr-x 12 root root 4096 Feb 23  2016 ..
drwxr-xr-x  2 pi   pi   4096 Apr 27 15:27 GCalData
```

**Comment by four2six** [comment]
seems to work ok now in 0.0.6

**Comment by allan-gam** [comment]
The error is due to that the raw Google Calendar json file has been deleted from /var/tmp/GCalData. That happened when You rebooted your server. (/var/tmp is probably a tmpfs)

GCal was sure that the file should exist and that it still didn't need to refresh it from Google. When You tried last time, the file should have been expired so GCal got you a new file from Google.

Anyway, I've made a new release that checks for that file's existence before trying to load it. So now, if the file is missing (whatever the reason ;) ) GCal just downloads a new one from Google!

**Comment by four2six** [comment]
perfect
