### ISSUE TITLE
Error running configurator

### ISSUE THREAD

**Issue by alexcf** [allan-gam/GCal#39]
Domoticz Time Zone :Europe/London
Domoticz text device Start Time format [%Y-%m-%d. From %H:%M to ]:
Domoticz text device End Time format [%H:%M]:
Domoticz text device All Day Event format [%Y-%m-%d. (All day event)]:
Domoticz web interface IP address (or host name) [192.168.1.253]:192.168.1.253
Domoticz web interface port number [8080]:
Domoticz web interface communication protocol (http or https) [http]:
Domoticz web interface user name (leave blank if no username is needed) :
Domoticz web interface password (leave blank if no password is needed) :
Send calendar data with SCP to username@host (leave blank if domoticz is installed on this machine) :
Send calendar data with SCP to remote directory (leave blank if domoticz is installed on this machine) :
Directory for app logging and storing access tokens [/var/tmp]:/tmp
Traceback (most recent call last):
  File "gcal.py", line 1365, in <module>
    main(sys.argv[1:])
  File "gcal.py", line 1341, in main
    global cfg; cfg = load_config()
  File "gcal.py", line 343, in load_config
    cfg = create_config()
  File "gcal.py", line 276, in create_config
    r = domoticzAPI(payload)
  File "gcal.py", line 366, in domoticzAPI
    if tty: print 'Unexpected status code from Domoticz: ' + r.status_code + ' Url: ' + r.url
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by allan-gam** [comment]
GCal is trying to list the hardware on Domoticz but it fails. What if you try the following command using the command line:

curl http://192.168.1.253:8080/json.htm?type=hardware

Does that work?

**Comment by alexcf** [comment]
OK, so some weird issues :).
1) doing http gives me a 401 Unauthorised, regardless of what I do, however https is fine.
2) moved to https which made a difference, although had crashes all over the place, turns out that because the certificate isn't "valid" on my local machine, and "verify=False" isn't on the requests.get statement it crashes. Adding verify=False sorted that out.
3) Forcing str() on status code and URL ensured that part didn't crash, but the next action is exit() so... :).
4) First time I ran the script it created switches for me. I removed those and re-added them, now I get nothing new.

**Comment by allan-gam** [comment]
Domoticz needs to be configured with Basic-Auth authentication for Authentication to work in GCal. If configured with Login Page, it'll show 'Unauthorized' even though your credentials match.

The host running GCal must be allowed to communicate properly with the Domoticz host using the [Domoticz API/JSON URL's](https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s). (The GCal host may be the same as the Domoticz host, but since you are using 192.168.1.253 instead of 127.0.0.1, I guess it's not)

So, if you are using authentication make sure to set the type to "basic-Auth" and not "Login Page". As an alternative, you could probably allow the GCal host to access the Domoticz host without username and password; e.g. set "Local Networks (no username/password)" to something similar to "127.0.0.*;192.168.1.*"

In case you are forcing HTTPS to be used for accessing the Domoticz host in your LAN for some reason, then you'll need a valid certificate or you can try to do as you already did, set "verify=False" on the request.

1. See above.
2. See above. However, I've added "verify=False" by default.
3. Str conversion has been added. That was a bug. exit() is the intended next action since we can not proceed in such a case.
4. Removing the config and starting from scratch sounds like a good solution if the communication and the API hasn't been working for some reason.
5. Script has been modified to properly handle if the summary element is missing.
6. Running the installation script as root has not been tested and it may lead to several different issues including wrong file permissions. If the fix that you suggested works, it seems to be a much better solution.

Script version updated to 0.9.3. Please let me know if there are any remaining issues.

**Comment by alexcf** [comment]
Awesome :). It is running on the same box, so IP address doesn't make much of a difference. I think one of the main things through reconfiguration which would be good (i.e. in case variables and dummy switches are deleted) to re-create the config/variables.
